/**
 * Created by shtiyu on 17/3/7.
 */
let question = [
    {answer:"布娃娃",tips:"三个字，儿童玩具"},
    {answer:"激光",tips:"两个字，光学武器"},
    {answer:"餐巾纸",tips:"三个字，餐具"},
    {answer:"仓库",tips:"两个字，建筑类"},
    {answer:"丁字裤",tips:"三个字，一种内衣"},
    {answer:"CD",tips:"两个字母，一种数据存储"},
    {answer:"蜂蜜",tips:"两个字，食品类"},
    {answer:"瓷器",tips:"两个字，容器类"},
    {answer:"人民币",tips:"三个字，货币类"},
    {answer:"手纸",tips:"两个字，日用品"},
    {answer:"沙漏",tips:"两个字，计时器类"},
    {answer:"雷人",tips:"两个字，网络语"},
    {answer:"除草剂",tips:"三个字，清除作用的药物"},
    {answer:"淘宝",tips:"两个字，电商"},
    {answer:"不入虎穴焉得虎子",tips:"八个字，俗语"},
    {answer:"原子弹",tips:"三个字，武器类"},
    {answer:"树苗",tips:"两个字，植物类"},
    {answer:"娃哈哈",tips:"三个字，儿童饮料"},
    {answer:"大头鱼",tips:"三个字，水产类"},
    {answer:"仙人掌",tips:"三个字，植物"},
    {answer:"手术刀",tips:"三个字，医疗器械"},
    {answer:"疯子",tips:"两个字，非正常人类"},
    {answer:"豆沙包",tips:"三个字，食品"},
    {answer:"射雕英雄传",tips:"五个字，古代小说"},
    {answer:"凤姐",tips:"两个字，网络名人"},
    {answer:"耳机",tips:"两个字，电子产品"},
    {answer:"钓鱼岛",tips:"三个字，中国固有领土"},
    {answer:"飞碟",tips:"两个字，交通工具"},
    {answer:"靖国神社",tips:"四个字，被称为岛国神侧"},
    {answer:"工资",tips:"两个字，劳动所得"},
    {answer:"蟾蜍",tips:"两个字，益虫"},
    {answer:"冰雹",tips:"两个字，天气术语"},
    {answer:"落井下石",tips:"成语，一种行为"},
    {answer:"僵尸",tips:"两个字，神话人物"},
    {answer:"游泳衣",tips:"三个字，服装类"},
    {answer:"齐白石",tips:"三个字，艺术家名字"},
    {answer:"呲牙咧嘴",tips:"四个字，一种表情"},
    {answer:"打火机",tips:"三个字，日用品"},
    {answer:"酒鬼",tips:"两个字，形容一个人的嗜好"},
    {answer:"外星人",tips:"三个字，一种生物"},
    {answer:"山楂",tips:"两个字，水果"},
    {answer:"山药",tips:"两个字，蔬菜类"},
    {answer:"牛奶",tips:"两个字，饮品"},
    {answer:"蹦极",tips:"两个字，体育运动"},
    {answer:"死不瞑目",tips:"成语，一种表情"},
    {answer:"色迷迷",tips:"三个字，形容一种表情"},
    {answer:"哈喇子",tips:"三个字，人体类"},
    {answer:"钓鱼",tips:"两个字，一种运动"},
    {answer:"花仙子",tips:"三个字，神话人物"},
    {answer:"兔女郎",tips:"三个字，一种角色"},
    {answer:"董存瑞",tips:"三个字，历史人物"},
    {answer:"日环食",tips:"三个字，天文现象"},
    {answer:"击剑",tips:"两个字，体育比赛"},
    {answer:"盗墓",tips:"两个字，一种非法行为"},
    {answer:"花前月下",tips:"成语，一种场景"},
    {answer:"春梦",tips:"两个字，一种生理现象"},
    {answer:"监狱",tips:"两个字，一种场合"},
    {answer:"贞子",tips:"两个字，神话人物"},
    {answer:"结婚证",tips:"三个字，一种证件"},
    {answer:"入洞房",tips:"三个字，人生乐事之一"},
    {answer:"空格键",tips:"三个字，电子部件"},
    {answer:"别墅",tips:"两个字，建筑类"},
    {answer:"KTV",tips:"三个字母，一种场合"},
    {answer:"人造卫星",tips:"四个字，人造天体"},
    {answer:"刘翔",tips:"两个字，人名"},
    {answer:"WC",tips:"两个字母，一种场所"},
    {answer:"挖鼻屎",tips:"三个字，一种行为"},
    {answer:"草泥马",tips:"三个字，一种动物"},
    {answer:"奶牛",tips:"两个字，动物类"},
    {answer:"帅哥",tips:"两个字，一种美称"},
    {answer:"插排",tips:"两个字，家用电器"},
    {answer:"癞蛤蟆",tips:"三个字，一种益虫"},
    {answer:"司马光",tips:"三个字，古代小英雄"},
    {answer:"电视购物",tips:"无提示"},
    {answer:"苍井空",tips:"铁拳的最爱"},
    {answer:"摩托车", tips:"无提示"},
    {answer:"小兔子", tips:"无提示"},
    {answer:"遛狗", tips:"无提示"},
    {answer:"摔倒", tips:"无提示"},
    {answer:"狗屁不通", tips:"无提示"},
    {answer:"大手大脚", tips:"无提示"},
    {answer:"垂头丧气", tips:"无提示"},
    {answer:"美女", tips:"无提示"},
    {answer:"放屁", tips:"无提示"},
    {answer:"打架", tips:"无提示"},
    {answer:"接吻", tips:"无提示"},
    {answer:"嚎啕大哭", tips:"无提示"},
    {answer:"张牙舞爪", tips:"无提示"},
    {answer:"太极", tips:"无提示"},
    {answer:"囧", tips:"无提示"},
    {answer:"回眸一笑", tips:"无提示"}
];

exports.getQuestion = function(){
    let length = question.length;
    let index  = Math.floor(Math.random() * length);
    return question[index];
};